version: '3.7'
services:
    jenkins:
        container_name: jenkins
        build: .
        restart: always
        volumes:
            - ./jenkins_data:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - ${DOCKER_BIN}:/usr/bin/docker:ro
            - ${DOCKER_COMPOSE_BIN}:/usr/bin/docker-compose:ro
        ports:
            - 8443:8443
            - 50000:50000
