version: '3.7'
services:
  minio:
    container_name: minio
    image: minio/minio
    volumes:
      - ./minio/data:/export
      - ./minio/config:/root/.minio
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: THISISEXAMPLEACCESSKEY
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCY
    networks:
      - minio
    entrypoint: sh
    command: -c 'mkdir -p /export/bucket_name && /usr/bin/minio server /export'
    deploy:
      restart_policy:
        condition: on-failure

networks:
  minio:
    external: true
